### ISSUE TITLE
Is it possible to add barcodes?

### ISSUE THREAD

**Issue by cvzi** [HopEdia/android-client#1]
I tried to search for some beers with barcodes, but none were found. But when I type in the name of the beer, it does exist. Is this feature working at all or are the barcodes just missing from the database?
If they are missing, can we add them somehow?

**Comment by koko-ng** [comment]
Yes, it's fully functional, you just need to tap "add it", then search and click on the name of the beer, save (in the menu) and the barcode will be added into the database. Unfortunately the database is still in lack of barcodes, but every modifications are welcome 😃.
I will try to improve a bit the UI for barcode, thanks for your report.
