### ISSUE TITLE
Login failes

### ISSUE THREAD

**Issue by cvzi** [HopEdia/android-client#2]
When I try to login it says:
"Server unreachable, verify your connection or try again later."
My connection is fine. Logcat is empty.

**Comment by koko-ng** [comment]
Sounds like a bug I have already corrected, what version are you using? Have you created an account?

**Comment by cvzi** [comment]
I am using 1.0.2
I just created an account in the app, and clicked on the link in the email.

**Comment by koko-ng** [comment]
Try to open the link you received and refresh the page and login on the website.

**Comment by cvzi** [comment]
How can I login on the website?
![clipboard01](https://cloud.githubusercontent.com/assets/8470684/17945324/a8011aba-6a43-11e6-9348-76a3bc7ce383.jpg)

Edit:
Website seems to work only in Firefox

**Comment by koko-ng** [comment]
Just tried on chrome, it isn't working :/. I will try to fix this as soon as I can, thanks a lot for your report. I will ping you when it is fixed, sorry.

**Comment by cvzi** [comment]
Yeah, I verified the account with Firefox and now it works in the app!

**Comment by koko-ng** [comment]
Oh great, hope you enjoy the app. I fixed the bug, closing the issue.
