### ISSUE TITLE
Add screenshots to F-Droid 

### ISSUE THREAD

**Issue by Korb** [HopEdia/android-client#6]
https://f-droid.org/packages/io.github.hopedia/
![Screenshot_2023_1104_171510_org fdroid fdroid](https://github.com/HopEdia/android-client/assets/3509797/fd8dc299-9f47-43ad-b9af-6742d61a104d)

**Comment by koko-ng** [comment]
Hi! Thanks for the suggestion, however this project is no longer maintained and the server has been down for years.
